{
	"version": 1633288664,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/ball-sheet0.png",
		"images/bullet-sheet0.png",
		"images/eyeball1-sheet0.png",
		"images/bg-sheet0.png",
		"images/bulletbounceicon-sheet0.png",
		"images/frogeye1-sheet0.png",
		"images/gravity-sheet0.png",
		"images/gravityoff-sheet0.png",
		"images/mouseobject-sheet0.png",
		"images/shield-sheet0.png",
		"images/spawner-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/bg1-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/shieldobject-sheet0.png",
		"images/shieldobject-sheet1.png",
		"images/shieldobject-sheet2.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/turret1-sheet0.png",
		"images/turretsomerkjøpt-sheet0.png",
		"images/walls-sheet0.png",
		"images/youfailed-sheet0.png",
		"images/particlesblaze.png",
		"images/particlesenemydie.png",
		"images/particlesgunfire.png",
		"images/particlesonhitball.png",
		"images/gasscloud-sheet0.png",
		"images/minesprite-sheet0.png",
		"images/minesprite-sheet1.png",
		"images/aoeareal-sheet0.png",
		"images/minesicon-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/particlesmineexplosion.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/overgang1-sheet0.png",
		"images/brainboss1-sheet0.png",
		"images/brainboss1-sheet1.png",
		"images/brainboss1-sheet2.png",
		"images/brainboss1-sheet3.png",
		"images/brainboss1-sheet4.png",
		"images/brainboss1-sheet5.png",
		"images/brainboss1-sheet6.png",
		"images/bossbullet1-sheet0.png",
		"images/bossbullet1-sheet1.png",
		"images/bossbullet1-sheet2.png",
		"images/bossbullet1-sheet3.png",
		"images/bossbullet1-sheet4.png",
		"images/bossbullet1-sheet5.png",
		"images/bossbullet1-sheet6.png",
		"images/bossturret-sheet0.png",
		"images/brainbosseyeleft-sheet0.png",
		"images/brainbosseyeright-sheet0.png",
		"images/enemybossspawner1-sheet0.png",
		"images/enemybossspawner1-sheet1.png",
		"images/enemybossspawner1-sheet2.png",
		"images/bossminion1-sheet0.png",
		"images/bossminion1-sheet1.png",
		"images/bossminion1-sheet2.png",
		"images/bossminion1-sheet3.png",
		"images/bossminion1-sheet4.png",
		"images/bossminion1-sheet5.png",
		"images/bossminion1-sheet6.png",
		"images/bossminion1-sheet7.png",
		"images/bossminion1-sheet8.png",
		"images/bossminion1-sheet9.png",
		"images/bossminion1-sheet10.png",
		"images/bossminion1-sheet11.png",
		"images/bossminion1-sheet12.png",
		"images/bossminion1-sheet13.png",
		"images/bossminion1-sheet14.png",
		"images/bossminion1-sheet15.png",
		"images/bossminion1-sheet16.png",
		"images/sprite10-sheet0.png",
		"images/sprite10-sheet1.png",
		"images/sprite10-sheet2.png",
		"images/sprite10-sheet3.png",
		"images/enemyminionblueturret-sheet0.png",
		"images/enemyminionblueturret-sheet1.png",
		"images/enemyminionblueturret-sheet2.png",
		"images/minionbluebullet-sheet0.png",
		"images/brainbosshealthbargreen-sheet0.png",
		"images/brainbosshealthbarred-sheet0.png",
		"images/playerhpgreen-sheet0.png",
		"images/playerhpgreen2-sheet0.png",
		"media/sfx1.ogg",
		"media/sfx 1.m4a",
		"media/lasorogg.ogg",
		"media/bgm3ogg.ogg",
		"media/music tape stop ogg.ogg",
		"media/enemy die ogg.ogg",
		"media/hit shield ogg.ogg",
		"media/ouch ogg.ogg",
		"media/tic toc ogg.ogg",
		"media/boom ogg.ogg",
		"media/tic toc 2 ogg.ogg",
		"media/enemy boost ogg.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}